# Generated by Django 2.2 on 2020-03-15 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 15, 50, 53, 403527, tzinfo=utc)),
        ),
    ]
