# Generated by Django 2.2 on 2020-03-15 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200315_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 15, 51, 18, 58408, tzinfo=utc)),
        ),
    ]
