# Generated by Django 2.2 on 2020-03-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20200316_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='orderDate',
        ),
    ]
