# Generated by Django 2.2 on 2020-03-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20200316_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.CharField(max_length=200),
        ),
    ]
