# Generated by Django 2.2 on 2020-03-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20200316_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='baseType',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
